<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Error</title>
</head>

<body>
	<?php if ('development' == $this->mode): ?>
		<h3>Message:</h3>
		<?php echo $this->exception->getMessage() ?>
	
	    <h3>Stack trace:</h3> 
	    <pre><?= (string)$this->exception ?></pre>
	
	    <h3>Request Parameters:</h3> 
	    <?php dd($this->request->getParams()) ?>
	<?php endif ?>
</body>

</html>