<div class="separate-page-header article">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<h3 class="mbr-section-title display-2"><?php echo $this->page['title_'.$this->language] ?></h3>
				
			</div>	
		</div>
	</div>
</div>
<div class="separate-page">
	<div class="container">
		<!-- <div class="row">
			<div class="col-xs-12">
		 -->			
				<?php echo $this->page['content_'.$this->language] ?>
				
		<!-- 	</div>	
		</div> -->
	</div>
</div>


