
<!-- <div class="normal-box"><?php echo $this->intContent; ?></div> -->
    <!-- <section class="mbr-section-full"> -->
        <div class="jarallax mbr-section-full mbr-section mbr-section-hero" style="background-image: url('<?php echo $this->baseUrl('/img/'.$this->theme.'/aussen-2000x1125-25.jpg');?>  ');">
            <div class="demo-table">
                <!-- <div class="demo-table-cell">
                    
                </div> -->
                <div class="mbr-table-cell">
                    <div class="container">
                        <div class="row">
                            <div class="mbr-section col-md-10 col-md-offset-1 text-xs-center">

                                <h1 class="mbr-section-title display-1"><?php echo Ct_Translate::_('header_slider_title'); ?></h1>
                                <p class="mbr-section-lead lead"><?php echo Ct_Translate::_('header_slider_text'); ?></p>
                                <div class="mbr-section-btn"><a class="btn btn-lg btn-primary" href="<?php echo $this->url(array('action'=>'index', 'controller'=>'index', 'module' => 'default'), 'default')?>#header3-c"><?php echo Ct_Translate::_('flat'); ?></a> <a class="btn btn-lg btn-white btn-white-outline" href="<?php echo $this->url(array('action'=>'index', 'controller'=>'index', 'module' => 'default'), 'default')?>#msg-box8-g"><?php echo Ct_Translate::_('location'); ?></a> <a class="btn btn-lg btn-white btn-white-outline" href="<?php echo $this->url(array('action'=>'index', 'controller'=>'index', 'module' => 'default'), 'default')?>#form1-i"><?php echo Ct_Translate::_('direction'); ?> &amp; <?php echo Ct_Translate::_('contact'); ?></a></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="mbr-arrow mbr-arrow-floating" aria-hidden="true">
                    <a href="#header3-c">
                        <i class="mbr-arrow-icon"></i>
                    </a>
                </div>
            </div>
        </div>
        
   <!--  </section> -->
    <section class="mbr-section mbr-section__container article" id="header3-c" style="background-color: rgb(255, 255, 255); padding-top: 80px; padding-bottom: 40px;">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h3 class="mbr-section-title display-2"><?php echo Ct_Translate::_('flat'); ?></h3>
                    
                </div>
            </div>
        </div>
    </section>

    <section class="mbr-section article mbr-section__container" id="content1-d" style="background-color: rgb(255, 255, 255); padding-top: 20px; padding-bottom: 20px;">

        <div class="container">
            <div class="row">
                <div class="col-xs-12 lead">
                    <p><?php echo Ct_Translate::_('flatsection1'); ?></p>
                    <p><?php echo Ct_Translate::_('flatsection2'); ?></p>
                    <p><?php echo Ct_Translate::_('flatsection3'); ?></p>
                    <p><?php echo Ct_Translate::_('flatsection4'); ?></p>
                    <p><?php echo Ct_Translate::_('flatsection5'); ?></p>
                </div>
            </div>
        </div>

    </section>

    <section class="mbr-cards mbr-section mbr-section-nopadding" id="features3-a" style="background-color: rgb(255, 255, 255);">
        <div class="mbr-cards-row row">
            <div class="mbr-cards-col col-xs-12 col-lg-3" style="padding-top: 80px; padding-bottom: 80px;">
                <div class="container">
                    <div class="card cart-block">
                        <div class="card-img"><img src="<?php echo $this->baseUrl('/img/'.$this->theme.'/hauptzimmer-600x337.jpg');?>" class="card-img-top"></div>
                        <div class="card-block">
                            <h4 class="card-title"><?php echo Ct_Translate::_('image1title'); ?></h4>
                            <p class="card-text"><?php echo Ct_Translate::_('image1decription'); ?></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="mbr-cards-col col-xs-12 col-lg-3" style="padding-top: 80px; padding-bottom: 80px;">
                <div class="container">
                    <div class="card cart-block">
                        <div class="card-img"><img src="<?php echo $this->baseUrl('/img/'.$this->theme.'/wohnkche-600x337.jpg');?>" class="card-img-top"></div>
                        <div class="card-block">
                            <h4 class="card-title"><?php echo Ct_Translate::_('image2title'); ?></h4>
                            <p class="card-text"><?php echo Ct_Translate::_('image2decription'); ?></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="mbr-cards-col col-xs-12 col-lg-3" style="padding-top: 80px; padding-bottom: 80px;">
                <div class="container">
                    <div class="card cart-block">
                        <div class="card-img"><img src="<?php echo $this->baseUrl('/img/'.$this->theme.'/badezimmer-600x337.jpg');?>" class="card-img-top"></div>
                        <div class="card-block">
                            <h4 class="card-title"><?php echo Ct_Translate::_('image3title'); ?></h4>
                            <p class="card-text"><?php echo Ct_Translate::_('image3decription'); ?></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="mbr-cards-col col-xs-12 col-lg-3" style="padding-top: 80px; padding-bottom: 80px;">
                <div class="container">
                    <div class="card cart-block">
                        <div class="card-img"><img src="<?php echo $this->baseUrl('/img/'.$this->theme.'/schlafzimmer-600x334.jpg');?>" class="card-img-top"></div>
                        <div class="card-block">
                            <h4 class="card-title"><?php echo Ct_Translate::_('image4title'); ?></h4>
                            <p class="card-text"><?php echo Ct_Translate::_('image4decription'); ?></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="jarallax mbr-section article" id="msg-box8-g" style="background-image: url('<?php echo $this->baseUrl('/img/'.$this->theme.'/basel-2000x667.jpg');?>');">
       
        <div class="mbr-overlay" style="opacity: 0.5; background-color: rgb(34, 34, 34);"></div>
        <!-- <div class="mbr-table-cell"> -->
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 text-xs-center">
                        <h3 class="mbr-section-title display-2 white"><?php echo Ct_Translate::_('location'); ?></h3>
                        <div class="lead-1">
                            <p><?php echo Ct_Translate::_('locationtextonimage'); ?></p>
                        </div>
                        
                    </div>
                </div>
            </div>
           
    </section>
    <section class="mbr-section article mbr-section__container" id="content1-f" style="background-color: rgb(255, 255, 255); padding-top: 20px; padding-bottom: 20px;">

        <div class="container">
            <div class="row">
                <div class="col-xs-12 lead">
                    <p><a href="http://binzen.de" target="_blank">Binzen</a> <?php echo Ct_Translate::_('locationtext_p1'); ?> <a href="http://basel.ch" target="_blank">Basel</a> (CH), 
                    <a href="http://mulhouse.fr" target="_blank">Muhlhouse</a> (F) <?php echo Ct_Translate::_('and'); ?> <a href="http://loerrach.de" target="_blank">Lörrach</a> (D) <?php echo Ct_Translate::_('locationtext_p2'); ?>:</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-5 lead">
                    <div class="article">
                        <p><span><?php echo Ct_Translate::_('bycartitle'); ?>:</span></p>
                        <p>- <?php echo Ct_Translate::_('bycarortaxi_1'); ?></p>
                        <p>- <?php echo Ct_Translate::_('bycarortaxi_2'); ?></p>
                        <p>- <?php echo Ct_Translate::_('bycarortaxi_3'); ?></p>
                    </div>
                    
                </div>
                <div class="col-lg-offset-1 col-lg-5 lead">
                    <div class="article">
                        <p><span><?php echo Ct_Translate::_('bybustitle'); ?></span></p>
                        <p>- <?php echo Ct_Translate::_('bybus_1'); ?></p>
                        <p>- <?php echo Ct_Translate::_('bybus_2'); ?></p>
                        <p>- <?php echo Ct_Translate::_('bybus_3'); ?></p>
                    </div>
                    
                </div>    
            </div>

        </div>

    </section>

    <section class="mbr-section" id="form1-i" style="background-color: rgb(255, 255, 255); padding-top: 120px; padding-bottom: 120px;">
        
        <div class="mbr-section mbr-section__container mbr-section__container--middle">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 text-xs-center">
                        <h3 class="mbr-section-title display-2"><?php echo Ct_Translate::_('contact'); ?></h3>
                        <small class="mbr-section-subtitle"><?php echo Ct_Translate::_('contactinfo'); ?></small>
                    </div>
                </div>
            </div>
        </div>
        <div class="mbr-section mbr-section-nopadding">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-lg-10 col-lg-offset-1" data-form-type="formoid">


                        <div data-form-alert="true">
                            <div data-form-alert-success="true" class="alert alert-form alert-success text-xs-center" hidden="">Ihre Nachricht wurde versandt.</div>
                        </div>
						
                        <form novalidate action="<?php echo $this->url(array('controller'=>'contact', 'action'=>'send', 'module'=>'default'), 'default');?>" method="post" data-form-title="Kontakt" id="contact_form">

                            <div class="row row-sm-offset">

                                <div class="col-xs-12 col-md-4">
                                    <div class="form-group">
                                        <label class="form-control-label" for="form1-i-name"><?php echo Ct_Translate::_('name'); ?><span class="form-asterisk">*</span></label>
                                        <input class="form-control" name="name" required="" data-form-field="Name" id="form1-i-name" type="text">
                                        <div id="id_name" class="at-error-msg"></div>
                                    </div>
                                </div>

                                <div class="col-xs-12 col-md-4">
                                    <div class="form-group">
                                        <label class="form-control-label" for="form1-i-email"><?php echo Ct_Translate::_('email'); ?><span class="form-asterisk">*</span></label>
                                        <input class="form-control" name="email" required="" data-form-field="Email" id="form1-i-email" type="email">
                                        <div id="id_email" class="at-error-msg"></div>
                                    </div>
                                </div>

                                <div class="col-xs-12 col-md-4">
                                    <div class="form-group">
                                        <label class="form-control-label" for="form1-i-phone"><?php echo Ct_Translate::_('phone'); ?></label>
                                        <input class="form-control" name="phone" data-form-field="Phone" id="form1-i-phone" type="tel">
                                    </div>
                                </div>

                            </div>

                            <div class="form-group">
                                <label class="form-control-label" for="form1-i-message"><?php echo Ct_Translate::_('message'); ?></label>
                                <textarea class="form-control" name="message" rows="7" data-form-field="Message" id="form1-i-message"></textarea>
                            </div>

                            <div><button type="submit" class="btn btn-primary"><span class="btn-text"><?php echo Ct_Translate::_('sendmessage'); ?></span><i class="btn-loader"></i></button></div>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </section>