<?php if ($this->params) $params = '?'.$this->params; else $params = ''; ?>
<?php if ($this->pageCount > 1): ?>
<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('module'=>$this->module, 'controller'=>$this->controller, 'action'=>$this->action, 'page' => $this->previous)).$params; ?>">&lt; Previous</a>
<?php else: ?>
  <span class="disabled">&lt; Previous</span>
<?php endif; ?>
 
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array('module'=>$this->module, 'controller'=>$this->controller, 'action'=>$this->action, 'page' => $page)).$params; ?>"><?php echo $page; ?></a>
  <?php else: ?>
    <span><?php echo $page; ?></span>
  <?php endif; ?>
<?php endforeach; ?>
 

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('module'=>$this->module, 'controller'=>$this->controller, 'action'=>$this->action, 'page' => $this->next)).$params; ?>">Next &gt;</a>
<?php else: ?>
  <span class="disabled">Next &gt;</span>
<?php endif; ?>
</div>
<?php endif; ?>